'use strict';
const fs=require('fs'),assert=require('assert');
const race=fs.readFileSync('race-setup.js','utf8');
const back=fs.readFileSync('track-backdrop.js','utf8');
const hook=fs.readFileSync('recovery-hook.js','utf8');
assert(race.includes('repeat(3,minmax(0,1fr))'));
assert(race.includes('raceShowGridCars'));
assert(race.includes('raceShowPitCars'));
assert(race.includes('GRID_CAR_OFFSETS'));
assert(race.includes('pitHeadingFromRoute'));
const drawSprite=race.slice(race.indexOf('function drawSprite'),race.indexOf('function drawCarFootprint'));
assert(drawSprite.indexOf('anchor(ctx')<drawSprite.indexOf('ctx.drawImage'),'race cursor must be drawn before positioned sprite');
assert(back.includes("mode.id='layerEditBackdrop'"));
assert(back.includes('Import IFF backdrop'));
assert(back.includes('Export backdrop .bin'));
assert(back.includes('TRACK_BYTES=TRACK_PLANE_BYTES*TRACK_PLANES'));
assert(back.includes('decodeByteRunRow'));
assert(hook.includes("s.src='track-backdrop.js'"));
console.log('Indy Heat v0.13 editor-extension UI tests OK');
