'use strict';
const fs=require('fs'),assert=require('assert');
const hook=fs.readFileSync('recovery-hook.js','utf8');
const backdrop=fs.readFileSync('track-backdrop.js','utf8');
assert(hook.includes('background:[]'));
assert(hook.includes('const decodePlanar=T.decodePlanar.bind(T)'));
assert(hook.includes('capture.background.push'));
assert(backdrop.includes('liveBackgroundCapture'));
assert(backdrop.includes('live.result.set(pixels)'));
assert(backdrop.includes("$('backgroundOpacity')"));
assert(backdrop.includes("redrawTrack(result.pixels)"));
assert(backdrop.includes('redrawTrack(decodeTrackPlanar(o))'));
assert(backdrop.includes("replace(/v0\\.(?:11|12|13|14)/i,'v0.15')"));
console.log('v0.15 live backdrop refresh regression tests OK');
