'use strict';
const fs=require('fs'),assert=require('assert');
const pkg=fs.readFileSync('circuit-package.js','utf8');
const patch=fs.readFileSync('editor-v0.16-integration.patch','utf8');
assert(pkg.includes("const VERSION=1"));
assert(pkg.includes('regionalMarkerX:0x4A'));
assert(pkg.includes('regionalMarkerY:0x4C'));
assert(pkg.includes('regionalMarkerFrame:0x4E'));
assert(pkg.includes("LAP_MIN=1"));assert(pkg.includes("LAP_MAX=99"));
assert(pkg.includes("circuit_${String(index).padStart(2,'0')}"));
assert(pkg.includes('return index<10?index+1:null'));
assert(pkg.includes("version:1,eventCount:11,entrySize:4,size:0x34"));
assert(pkg.includes("version:2,eventCount:11,entrySize:4,size:0x34"));
assert(pkg.includes('the 1.3 test-15 slave intentionally does NOT consume'));
assert(pkg.includes("runtimeRaceSetup:'race_setup.bin'"));
assert(pkg.includes("regionalSelectorIsGenerated:true"));
assert(patch.includes("s.src='circuit-package.js'"));
assert(patch.includes("data-indyheat-circuit-package"));
assert(patch.includes("clampInt(values.laps,1,99,'Lap count')"));
assert(patch.includes('id="raceLaps" type="number" min="1" max="99"'));
console.log('Indy Heat v0.16 integration static checks OK');
