'use strict';
const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('recovery-editor.js','utf8');
assert(html.includes('id="legacyRecoveryControls" hidden'));
assert(!html.includes('>Phase <input id="headingPhase"'));
assert(!html.includes('Reverse rotation</label>'));
assert(html.includes('recovery-hook.js'));
assert(html.includes('recovery-editor.js'));
assert(html.includes('authentic 40×28'));
assert(js.includes("mode.id='layerEditRecovery'"));
assert(js.includes('repeat(4,1fr)'));
assert(js.includes('recoveryShowDormant'));
assert(js.includes('cellIntersectsSurfaceClass'));
assert(js.includes("canvas.addEventListener('contextmenu'"));
assert(js.includes("id=\"recoveryGrabGroup\""));
assert(js.includes("id=\"recoveryClearGroup\""));
assert(js.includes('selectedGroup=new Set'));
assert(js.includes('toggleGroupCell'));
assert(js.includes('Grab group active'));
assert(js.includes('Clear group returns to single-cell editing'));
assert(!js.includes('left-drag selects a rectangle'));
assert(!js.includes('recoveryClearSelection'));
assert(!js.includes('strokeRect(x0'));
console.log('Recovery editor UI tests OK');
